### ISSUE TITLE
args[0] is not the name of the project file

### ISSUE THREAD

**Issue by smartinstot** [JoshuaSFryer/agent_soccer_team#1]
```
// args[0] is name of project file
// Parse that file and get a list of agent names
List<String> agent_names = getAgentNames(args[0]);
for (String name : agent_names) {
     logger.info("Agent present: " + name);
}
```
In SoccerEnvironment causes a error in Jason, args[0] is not the project file. Can you run this code and make sure its enumerating the agents properly.
```

[CentralisedEnvironment] Error in Centralised MAS environment creation
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at SoccerEnvironment.init(SoccerEnvironment.java:44)
	at jason.infra.centralised.CentralisedEnvironment.<init>(CentralisedEnvironment.java:33)
	at jason.infra.centralised.RunCentralisedMAS.createEnvironment(RunCentralisedMAS.java:452)
	at jason.infra.centralised.RunCentralisedMAS.create(RunCentralisedMAS.java:232)
	at jason.infra.centralised.RunCentralisedMAS.main(RunCentralisedMAS.java:90)

Exception in thread "main" jason.JasonException: The user environment class instantiation 'SoccerEnvironment' has failed!Index 0 out of bounds for length 0
	at jason.infra.centralised.CentralisedEnvironment.<init>(CentralisedEnvironment.java:36)
	at jason.infra.centralised.RunCentralisedMAS.createEnvironment(RunCentralisedMAS.java:452)
	at jason.infra.centralised.RunCentralisedMAS.create(RunCentralisedMAS.java:232)
	at jason.infra.centralised.RunCentralisedMAS.main(RunCentralisedMAS.java:90)
```

**Comment by JoshuaSFryer** [comment]
Resolved; needed to pass the file name in the mas2j file
